version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    networks:
      - app_net

  keycloak:
    image: jboss/keycloak:11.0.3
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: users
      DB_USER: postgres
      DB_PASSWORD: example
      KEYCLOAK_USER: kcadmin
      KEYCLOAK_PASSWORD: kcpass
    ports:
      - 8081:8080
    networks:
      - app_net

networks:
  app_net:
    driver: bridge